CREATE TABLE days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(tags) = 'array'),
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    parent_id BIGINT REFERENCES tasks(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    position INTEGER NOT NULL DEFAULT 0 CHECK(position >= 0),
    client_id TEXT UNIQUE,
    CHECK(length(btrim(content)) > 0 OR jsonb_array_length(tags) > 0)
);
CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id BIGINT NOT NULL REFERENCES days(id),
    content TEXT NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(tags) = 'array'),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    source_task_id BIGINT UNIQUE REFERENCES tasks(id) DEFERRABLE INITIALLY DEFERRED,
    client_id TEXT UNIQUE,
    parent_id BIGINT,
    position INTEGER NOT NULL DEFAULT 0 CHECK(position >= 0),
    UNIQUE(id, day_id),
    FOREIGN KEY(parent_id, day_id) REFERENCES notes(id, day_id) ON DELETE SET NULL (parent_id) DEFERRABLE INITIALLY DEFERRED,
    CHECK(length(btrim(content)) > 0 OR jsonb_array_length(tags) > 0)
);
CREATE INDEX notes_day ON notes(day_id, position, id);
CREATE INDEX notes_parent_order ON notes(parent_id, position, id);
CREATE INDEX tasks_parent_order ON tasks(parent_id, position, id);
CREATE INDEX notes_tags ON notes USING gin(tags);
CREATE INDEX tasks_tags ON tasks USING gin(tags);
CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    CHECK(ended_at IS NULL OR ended_at >= started_at),
    EXCLUDE USING gist (tstzrange(started_at, ended_at, '[)') WITH &&)
);
CREATE UNIQUE INDEX one_running_session ON sessions((1)) WHERE ended_at IS NULL;
CREATE INDEX sessions_start ON sessions(started_at);
CREATE TABLE document_operations (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    undone BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE document_changes (
    operation_id TEXT NOT NULL REFERENCES document_operations(id),
    entity TEXT NOT NULL CHECK(entity IN ('notes', 'tasks')),
    row_id BIGINT NOT NULL,
    phase TEXT NOT NULL CHECK(phase IN ('before', 'after')),
    present BOOLEAN NOT NULL,
    content TEXT, tags JSONB, day_id BIGINT, parent_id BIGINT, position INTEGER,
    created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ, completed_at TIMESTAMPTZ,
    source_task_id BIGINT, client_id TEXT,
    PRIMARY KEY(operation_id, entity, row_id, phase)
);

-- Deferred checks examine the final tree, allowing undo and imports to restore
-- parents and children in one transaction without accepting cycles or deep trees.
CREATE FUNCTION validate_bullet_tree() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE ancestor_depth INTEGER; child_depth INTEGER; cycle_found BOOLEAN;
BEGIN
    EXECUTE format('WITH RECURSIVE ancestors AS (
        SELECT id, parent_id, 1 AS depth, ARRAY[id] AS path, false AS cycle FROM %I WHERE id = $1
        UNION ALL SELECT p.id, p.parent_id, a.depth + 1, a.path || p.id, p.id = ANY(a.path)
        FROM %I p JOIN ancestors a ON p.id = a.parent_id WHERE NOT a.cycle
    ) SELECT max(depth), bool_or(cycle) FROM ancestors', TG_TABLE_NAME, TG_TABLE_NAME)
    INTO ancestor_depth, cycle_found USING NEW.id;
    IF cycle_found THEN
        RAISE EXCEPTION 'Bullet hierarchy cannot contain a cycle' USING ERRCODE = '23514';
    END IF;
    EXECUTE format('WITH RECURSIVE children AS (
        SELECT id, 0 AS depth FROM %I WHERE id = $1
        UNION ALL SELECT c.id, p.depth + 1 FROM %I c JOIN children p ON c.parent_id = p.id WHERE p.depth < 8
    ) SELECT max(depth) FROM children', TG_TABLE_NAME, TG_TABLE_NAME)
    INTO child_depth USING NEW.id;
    IF ancestor_depth + child_depth > 8 THEN
        RAISE EXCEPTION 'Bullets support up to eight levels' USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER notes_valid_tree AFTER INSERT OR UPDATE ON notes
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_bullet_tree();
CREATE CONSTRAINT TRIGGER tasks_valid_tree AFTER INSERT OR UPDATE ON tasks
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_bullet_tree();
